[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "orchard_tree_templating"
version = "0.0.1"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Marcus Rosette", email = "rosettem@oregonstate.edu" },
]
maintainers = [
    { name = "Marcus Rosette", email = "rosettem@oregonstate.edu" },
]
description = "A package to perform orchard SLAM and place tree templates at mapped trunk locations"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "optuna",
    "utm",
    "pyyaml"
]